# Generated by Django 5.2 on 2025-04-07 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menulink',
            name='text',
            field=models.CharField(max_length=50),
        ),
    ]
